---
deployment:
  tasks:
    - 'if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then export DEPLOYPATH=/home/eposrs/servis-epos-app/; else export DEPLOYPATH=/home/eposrs/develop-servis-epos-app/; fi'
    - '/usr/bin/rsync -a --delete --exclude=''/.*'' --exclude=/storage/ --exclude=/public/bl/ --exclude=/public/predracuni/ --exclude=/public/storage --exclude=/public/hot --exclude=/node_modules/ ./ $DEPLOYPATH'
    - /bin/rm -f $DEPLOYPATH/bootstrap/cache/packages.php $DEPLOYPATH/bootstrap/cache/services.php $DEPLOYPATH/bootstrap/cache/config.php $DEPLOYPATH/bootstrap/cache/compiled.php
    - /bin/rm -f $DEPLOYPATH/storage/framework/views/*.php
